<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateAverageMentorRatingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('average_mentor_ratings', function (Blueprint $table) {
            // this should be an autogenerated matrix kind of
            // it being a table might be tricky
            // let's leave it pending for a while
            // meanwhile just add some attributes to create the table, which will be modified later

            $table->increments("amr_id");

            $table->integer("std_id")->unsigned();
            $table->foreign("std_id")->references("std_id")->on("students");
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('average_mentor_ratings');
    }
}